### ISSUE TITLE
Artist tag restriction on characters

### ISSUE THREAD

**Issue by sriharsha-y** [NiKoTron/dart-tags#4]
When i try to include a string greater than or equal to 46 bytes, the writing fails on that mp3 file. It may be true for other tags as well, but observed this on artist tag as am having quite lengthy strings in there.

**Example artist string which writes successfully:**

Ilaiyaraaja, K. S. Chithra, S. P. Balasubrahmanyam

**Example artist string which fails:**

Ilaiyaraaja, K. S. Chithra, S. P. BalasubrahmanyamT

**Comment by NiKoTron** [comment]
Hello @sriharsha-y! Thanks for reporting! Could you please tell me which tag version do you tried to write? And what do you mean fails, is it runtime exception, or smth. else?

Anyway, if you tried to write ID3v1.x, it should truncate your string up to 30 characters. It's expected behaviour according to id3v1 specification.

**Comment by sriharsha-y** [comment]
Hi @NiKoTron, it does not throw any runtime exception. But it fails to write the tag and when i try to read the file it does not have any meta data in it (mp3 file did not get corrupted though). I used ID3v2.4

Will try to upgrade to the latest version and check.

**Comment by NiKoTron** [comment]
@sriharsha-y you could also check this test case.
UPD: https://github.com/NiKoTron/dart-tags/blob/f5b3242a7e09c2642a0b898bd50cf4817be64a87/test/dart_tags_test.dart#L249

**Comment by NiKoTron** [comment]
@sriharsha-y, is it ok? could I close this issue?
